server:
  port: 6001

spring:
  application:
    name: wms-api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        # Tenant Service Routes
        - id: tenant-service-tenants
          uri: lb://WMS-TENANT-SERVICE
          predicates:
            - Path=/api/v1/tenants/**
        - id: tenant-service-roles
          uri: lb://WMS-TENANT-SERVICE
          predicates:
            - Path=/api/v1/roles/**
        - id: tenant-service-teams
          uri: lb://WMS-TENANT-SERVICE
          predicates:
            - Path=/api/v1/teams/**
        - id: tenant-service-users
          uri: lb://WMS-TENANT-SERVICE
          predicates:
            - Path=/api/v1/users/**
        # Warehouse Service Routes
        - id: warehouse-service
          uri: lb://WMS-WAREHOUSE-SERVICE
          predicates:
            - Path=/api/v1/warehouses/**
        # Product Service Routes
        - id: product-service
          uri: lb://WMS-PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        # Inventory Service Routes
        - id: inventory-service
          uri: lb://WMS-INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
        # Order Service Routes
        - id: order-service
          uri: lb://WMS-ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/
  instance:
    prefer-ip-address: true