server:
  port: 6001

spring:
  application:
    name: wms-api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        # Tenant Service Routes
        - id: tenant-service-tenants
          uri: lb://WMS-TENANT-SERVICE
          predicates:
            - Path=/api/v1/tenants/**
        - id: tenant-service-tenant-settings
          uri: lb://WMS-TENANT-SERVICE
          predicates:
            - Path=/api/v1/tenant-settings/**
        - id: tenant-service-user-role-mappings
          uri: lb://WMS-TENANT-SERVICE
          predicates:
            - Path=/api/v1/user-role-mappings/**
        # Warehouse Service Routes - Hierarchical order
        - id: warehouse-service-warehouses
          uri: lb://WMS-WAREHOUSE-SERVICE
          predicates:
            - Path=/api/v1/warehouses/**
        - id: warehouse-service-floors
          uri: lb://WMS-WAREHOUSE-SERVICE
          predicates:
            - Path=/api/v1/floors/**
        - id: warehouse-service-zones
          uri: lb://WMS-WAREHOUSE-SERVICE
          predicates:
            - Path=/api/v1/zones/**
        - id: warehouse-service-aisles
          uri: lb://WMS-WAREHOUSE-SERVICE
          predicates:
            - Path=/api/v1/aisles/**
        - id: warehouse-service-racks
          uri: lb://WMS-WAREHOUSE-SERVICE
          predicates:
            - Path=/api/v1/racks/**
        - id: warehouse-service-shelves
          uri: lb://WMS-WAREHOUSE-SERVICE
          predicates:
            - Path=/api/v1/shelves/**
        - id: warehouse-service-bins
          uri: lb://WMS-WAREHOUSE-SERVICE
          predicates:
            - Path=/api/v1/bins/**
        # Product Service Routes
        - id: product-service
          uri: lb://WMS-PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        # Inventory Service Routes
        - id: inventory-service-storage-items
          uri: lb://WMS-INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/storage-items/**
        - id: inventory-service
          uri: lb://WMS-INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
        # Order Service Routes
        - id: order-service
          uri: lb://WMS-ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        # File Service Routes
        - id: file-service
          uri: lb://WMS-FILE-SERVICE
          predicates:
            - Path=/api/v1/files/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.wmspro.gateway: DEBUG
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: WARN
    reactor.netty.http.server: INFO