server:
  port: 6001

spring:
  application:
    name: wms-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: tenant-service
          uri: lb://TENANT-SERVICE
          predicates:
            - Path=/api/tenants/**
        - id: warehouse-service
          uri: lb://WAREHOUSE-SERVICE
          predicates:
            - Path=/api/warehouses/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventory/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/
  instance:
    prefer-ip-address: true